"""Primary key generation.

Keys are generated by the application, not by database sequences, so every node
of the Spock mesh can insert without coordination (ADR 0006).
"""

from __future__ import annotations

import os
import threading
import time
import uuid

_lock = threading.Lock()
_last_ms = 0
_last_rand_a = 0


def uuid7() -> uuid.UUID:
    """Return an RFC 9562 version 7 UUID: 48-bit Unix milliseconds, then random bits.

    Keys created in the same millisecond by this process keep increasing, which keeps
    B-tree inserts local. Python 3.12 has no uuid.uuid7, hence this helper.
    """
    global _last_ms, _last_rand_a
    with _lock:
        ms = time.time_ns() // 1_000_000
        if ms > _last_ms:
            rand_a = int.from_bytes(os.urandom(2), "big") & 0x0FFF
        else:
            # Same (or earlier, after a clock step) millisecond: bump the 12-bit counter
            # and borrow from the timestamp if it overflows.
            ms = _last_ms
            rand_a = _last_rand_a + 1
            if rand_a > 0x0FFF:
                ms += 1
                rand_a = 0
        _last_ms, _last_rand_a = ms, rand_a
    rand_b = int.from_bytes(os.urandom(8), "big") & 0x3FFF_FFFF_FFFF_FFFF
    value = (ms & 0xFFFF_FFFF_FFFF) << 80 | 0x7 << 76 | rand_a << 64 | 0b10 << 62 | rand_b
    return uuid.UUID(int=value)
